/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=wrangler-types.env --include-runtime=false` (hash: 8684cb6e837db96b8fbd9897f623de2e)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	CODELOUD_INTEREST_HOSTNAMES: "localhost,127.0.0.1" | "codeloud.xyz";
	CODELOUD_INTEREST_DB?: D1Database;
	TURNSTILE_SITE_KEY?: "0x4AAAAAAESQJEws32hnSB2M";
	RELAY_SERVICE?: Fetcher /* relay-mcp-production */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface LocalEnv {
		ASSETS: Fetcher;
		CODELOUD_INTEREST_HOSTNAMES: "localhost,127.0.0.1";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CODELOUD_INTEREST_HOSTNAMES" | "TURNSTILE_SITE_KEY">> {}
}
